import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen gap-8 flex flex-col justify-center items-center p-4">
      <h1 className="font-black italic font-serif text-4xl">Vowify</h1>
      {children}
    </div>
  );
}
