import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen flex flex-col justify-center items-center">
      <div className="container lg:w-1/3 p-6 border rounded-2xl bg-background shadow-xl">
        {children}
      </div>
    </div>
  );
}
